// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiInsight struct {
	ID                   uuid.UUID          `json:"id"`
	DecisionID           uuid.UUID          `json:"decision_id"`
	ModelVersion         string             `json:"model_version"`
	TriggerContext       string             `json:"trigger_context"`
	InsightText          string             `json:"insight_text"`
	PrimaryBias          pgtype.Text        `json:"primary_bias"`
	EmotionalTone        pgtype.Text        `json:"emotional_tone"`
	RiskLevel            pgtype.Text        `json:"risk_level"`
	ActionabilityScore   pgtype.Int4        `json:"actionability_score"`
	SuggestedAlternative pgtype.Text        `json:"suggested_alternative"`
	ModelConfidence      pgtype.Float4      `json:"model_confidence"`
	GeneratedAt          pgtype.Timestamptz `json:"generated_at"`
}

type Decision struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	Title               string             `json:"title"`
	Context             pgtype.Text        `json:"context"`
	ConfidenceBefore    pgtype.Int4        `json:"confidence_before"`
	ScheduledReviewDate pgtype.Date        `json:"scheduled_review_date"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type DecisionOutcome struct {
	DecisionID     uuid.UUID          `json:"decision_id"`
	ChosenOptionID uuid.UUID          `json:"chosen_option_id"`
	CommitmentNote pgtype.Text        `json:"commitment_note"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
}

type DecisionTag struct {
	DecisionID uuid.UUID          `json:"decision_id"`
	TagID      uuid.UUID          `json:"tag_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Evaluation struct {
	ID                uuid.UUID          `json:"id"`
	DecisionID        uuid.UUID          `json:"decision_id"`
	SatisfactionAfter pgtype.Int4        `json:"satisfaction_after"`
	ConfidenceAfter   pgtype.Int4        `json:"confidence_after"`
	HindsightNotes    pgtype.Text        `json:"hindsight_notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type LocalCredential struct {
	UserID       uuid.UUID          `json:"user_id"`
	PasswordHash string             `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OauthIdentity struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Option struct {
	ID         uuid.UUID          `json:"id"`
	DecisionID uuid.UUID          `json:"decision_id"`
	Title      string             `json:"title"`
	Pros       pgtype.Text        `json:"pros"`
	Cons       pgtype.Text        `json:"cons"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Token      string             `json:"token"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID       uuid.UUID   `json:"id"`
	UserID   uuid.UUID   `json:"user_id"`
	Name     string      `json:"name"`
	ColorHex pgtype.Text `json:"color_hex"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
