// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDecision = `-- name: CreateDecision :one

INSERT INTO decisions (user_id, title) 
VALUES ($1, $2) 
RETURNING id
`

type CreateDecisionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

// ==========================================
// DECISION QUERIES
// ==========================================
func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDecision, arg.UserID, arg.Title)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createLocalCredential = `-- name: CreateLocalCredential :exec
INSERT INTO local_credentials (user_id, password_hash) 
VALUES ($1, $2)
`

type CreateLocalCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateLocalCredential(ctx context.Context, arg CreateLocalCredentialParams) error {
	_, err := q.db.Exec(ctx, createLocalCredential, arg.UserID, arg.PasswordHash)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token, user_agent, ip_address, expires_at) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, display_name) 
VALUES ($1, $2) 
RETURNING id, email, display_name, created_at
`

type CreateUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

// ==========================================
// USER & AUTH QUERIES
// ==========================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getDecisionsByUserId = `-- name: GetDecisionsByUserId :many
SELECT id, user_id, title, context, confidence_before, scheduled_review_date, created_at, updated_at 
FROM decisions 
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetDecisionsByUserIdRow struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	Title               string             `json:"title"`
	Context             pgtype.Text        `json:"context"`
	ConfidenceBefore    pgtype.Int4        `json:"confidence_before"`
	ScheduledReviewDate pgtype.Date        `json:"scheduled_review_date"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDecisionsByUserId(ctx context.Context, userID uuid.UUID) ([]GetDecisionsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getDecisionsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDecisionsByUserIdRow
	for rows.Next() {
		var i GetDecisionsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Context,
			&i.ConfidenceBefore,
			&i.ScheduledReviewDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT password_hash 
FROM local_credentials 
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetPasswordHash(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordHash, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT user_id, expires_at 
FROM sessions 
WHERE token = $1 AND expires_at > NOW() LIMIT 1
`

type GetSessionByTokenRow struct {
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, created_at 
FROM users 
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}
